name: Desplegar en App Runner
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Iniciar sesión en AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Recuperar imagen desde Docker Hub
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/venceya:my-image-tag
    - name: Actualizar capacidad en App Runner
      run: aws apprunner update-service --service-arn my-apprunner-service-arn --instance-configuration Cpu=256,Memory=2048
